#!/bin/sh

echo "Running pre-push hook"

# Get current branch
BRANCH=$(git rev-parse --abbrev-ref HEAD)

echo "Current branch: $BRANCH"

#prevent push to test
if [ "$BRANCH" = "test" ]; then
    echo "You cannot push to test"
    exit 1
fi
