#!/bin/sh

echo "Running pre-push hook"


# Get current branch
BRANCH=$(git rev-parse --abbrev-ref HEAD)
AUTHOR=$(git config user.name)


#prevent push to test if branch is not test and author is not Germain
if [ "$BRANCH" != "test" ] && [ "$AUTHOR" != "Germain" ]; then
    echo "You are not allowed to push to $BRANCH (sorry $AUTHOR)"
    exit 1
fi
